---
- name: ANSISTRANO | GIT | Update remote repository
  git: repo={{ ansistrano_git_repo }} dest={{ ansistrano_deploy_to }}/shared version={{ ansistrano_git_branch }} accept_hostkey=true update=yes

- name: ANSISTRANO | GIT | Deploy git stored code to servers
  git: repo={{ ansistrano_deploy_from }} dest={{ ansistrano_release_path.stdout }} accept_hostkey=true
